### ISSUE TITLE
probes.spec.cy.js sometimes fails to find and delete `probe2`

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#285]
Maybe related to #252 

All three runs of the Cypress workflow failed in the probes.spec.cy at https://github.com/sundeck-io/OpsCenter/actions/runs/6116849685/job/16621519811?pr=260 (this PR was workflow-only changes which are essentially a no-op).

```
1) Probes section
       Menu: Probes:
     CypressError: Timed out retrying after 20000ms: `cy.contains()` failed because the page updated as a result of this command, but you tried to continue the command chain. The subject is no longer attached to the DOM, and Cypress cannot requery the page after commands such as `cy.contains()`.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You can typically solve this by breaking up a chain. For example, rewrite:

> `cy.get('button').click().should('have.class', 'active')`

to

> `cy.get('button').as('btn').click()`
> `cy.get('@btn').should('have.class', 'active')`

https://on.cypress.io/element-has-detached-from-dom
      at isAttached (http://localhost:8501/__cypress/runner/cypress_runner.js:161657:66)
      at validateType (http://localhost:8501/__cypress/runner/cypress_runner.js:161527:9)
      at Object.isType (http://localhost:8501/__cypress/runner/cypress_runner.js:161562:7)
      at <unknown> (http://localhost:8501/__cypress/runner/cypress_runner.js:148763:22)
      at Object.subjectFn (http://localhost:8501/__cypress/runner/cypress_runner.js:159523:16)
      at $Cy.verifyUpcomingAssertions (http://localhost:8501/__cypress/runner/cypress_runner.js:140576:31)
      at onRetry (http://localhost:8501/__cypress/runner/cypress_runner.js:159514:15)
      at tryCatcher (http://localhost:8501/__cypress/runner/cypress_runner.js:18744:23)
      at Promise.attempt.Promise.try (http://localhost:8501/__cypress/runner/cypress_runner.js:16018:29)
      at whenStable (http://localhost:8501/__cypress/runner/cypress_runner.js:156384:65)
      at <unknown> (http://localhost:8501/__cypress/runner/cypress_runner.js:155825:14)
      at tryCatcher (http://localhost:8501/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:8501/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:8501/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:8501/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:8501/__cypress/runner/cypress_runner.js:16861:18)
      at Promise._fulfill (http://localhost:8501/__cypress/runner/cypress_runner.js:16805:18)
      at <unknown> (http://localhost:8501/__cypress/runner/cypress_runner.js:[184](https://github.com/sundeck-io/OpsCenter/actions/runs/6116849685/job/16621519811?pr=260#step:10:185)19:46)
  From Your Spec Code:
      at probeDelete (webpack:///./cypress/support/utils.js:91:5)
      at Context.eval (webpack:///./cypress/e2e/probes.spec.cy.js:61:16)
```

I ran this locally and can (usually) see the same thing. The symptoms seem to be that Cypress is unable to find the element on the page with the Probe name (and then scroll to it). It's not clear to me what is actually happening.

**Comment by vqmarkman** [comment]
I was able to reproduce this locally.
