### ISSUE TITLE
Exception "index 0 is out of bounds for axis 0 with size 0" seen on Task Settings Page

### ISSUE THREAD

**Issue by joshelser** [sundeck-io/OpsCenter#35]
```
2023-07-06 21:22:17.107 Uncaught app exception
Traceback (most recent call last):
  File "$HOME/Library/Caches/pypoetry/virtualenvs/opscenter-g7Dx2M1v-py3.8/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "$HOME/OpsCenter/app/ui/pages/10_Settings.py", line 109, in <module>
    setup.setup_block()
  File "$HOME/OpsCenter/app/ui/setup.py", line 54, in setup_block
    connection.execute(
IndexError: index 0 is out of bounds for axis 0 with size 0
```

It doesn't appear that this should be able to happen under normal circumstances. The hunch is that it is related to interacting with the page before Streamlit has completely loaded the page.

**Comment by vqmarkman** [comment]
Another similar issue that we will track here is: "Exception when clicking on Warehouses tab/Heatmap and choosing 7 day range"

```
2023-07-06 16:29:37.456 Uncaught app exception
Traceback (most recent call last):
  File "/Users/vickymarkman/Library/Caches/pypoetry/virtualenvs/opscenter-g7Dx2M1v-py3.8/lib/python3.8/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/Users/vickymarkman/git-repo/OpsCenter/app/ui/pages/01_Warehouses.py", line 13, in <module>
    reports.display(options)
  File "/Users/vickymarkman/git-repo/OpsCenter/app/ui/reports.py", line 30, in display
    options[report](filter_values, credit_cost)
  File "/Users/vickymarkman/git-repo/OpsCenter/app/ui/reports_heatmap.py", line 31, in heatmap
    df["UTILIZATION"] = (df["UTILIZATION"].astype(float) * 100).round(1)
  File "/Users/vickymarkman/Library/Caches/pypoetry/virtualenvs/opscenter-g7Dx2M1v-py3.8/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/vickymarkman/Library/Caches/pypoetry/virtualenvs/opscenter-g7Dx2M1v-py3.8/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'UTILIZATION'
```

We need to find a way to be more resilient when page is refreshing according to Ryan.
